package de.iip_ecosphere.platform.examples.energy;

import java.io.InputStream;

import de.iip_ecosphere.platform.services.environment.AbstractGenericServicePluginDescriptor;
import de.iip_ecosphere.platform.services.environment.ServiceKind;

import iip.datatypes.OpcOut;
import iip.impl.OPCReceiverImpl;

/**
 * Service implementation for net node 'OPC Receiver'.
 * Generated by: EASy-Producer.
 */
public class ReceiverImpl extends OPCReceiverImpl {

    /**
     * JSL descriptor for dynamic loading.
     */
    public static class Descriptor extends AbstractGenericServicePluginDescriptor<ReceiverImpl> {

        /**
         * Creates the instance for JSL.
         */
        public Descriptor() {
            super(PLUGIN_ID_APP_SERVICE_PREFIX + SERVICE_ID, ReceiverImpl.class);
        }

        @Override
        public ReceiverImpl createService(String serviceId, InputStream ymlFile) {
            return new ReceiverImpl(serviceId, ymlFile);
        }

        @Override
        public ReceiverImpl createService() {
            return new ReceiverImpl();
        }

    }

    /**
     * Fallback constructor, also used for testing main program.
     */
    public ReceiverImpl() {
        super(ServiceKind.SINK_SERVICE);
    }

    /**
     * Creates a service instance from a service id and a YAML artifact.
     *
     * @param serviceId the service id
     * @param ymlFile the YML file containing the YAML artifact with the service descriptor
     */
    public ReceiverImpl(String serviceId, InputStream ymlFile) {
        super(serviceId, ymlFile);
    }

    @Override
    public void processOpcOut(OpcOut data) {
        // TODO Store, emit, pass on your data here. This is the sink.
    }

}
